### ISSUE TITLE
Support for errors raised after button clicks?

### ISSUE THREAD

**Issue by fxb-creator** [JoschuaSchneider/use-error-boundary#31]
Hi,

I played around with **use-error-boundary** - especially using the variant "without using render props".
It workes fine when raising errors inside the functional components. 👍 😄 

What I couldn't achive is the interception of an error when I call a function after a button click.
E.g.:
```
<>
 {didCatch ? ( <ErrorOutput error={error} />
  ) : (
  <ErrorBoundary>
      <button onClick={() => {throw Error("myClick Error");}}>Throw new Error</button>
  </ErrorBoundary>
 )}
</>
```
My experience: when I click on the button the error is thrown - but not shown in my ErrorOutput component (like other errors)

Did I something wrong - or is this case not supported by this package?

**Comment by JoschuaSchneider** [comment]
This is not supported by this package or error boundaries in general.

React error boundaries are designed to catch Exceptions that are raised during the render phase.

Callbacks, effects and other asynchronous operations happen outside of the rendering process and you have to handle them manually.

---

If you want to depend on error boundaries for those kind of errors you would have to keep track of the error state inside your component and re-throw the exception on component level.

Here is how this could look like as a custom hook:

```ts
const useThrowError = () => {
  const [, setState] = useState();

  return useCallback(
    (error: Error) =>
      setState(() => {
        throw error;
      }),
    [setState]
  );
};


const Component = () => {
  const throwError = useThrowError();

  return (
    <button
      onClick={() => {
        throwError(new Error("Exception here :)"));
      }}
    >
      boom
    </button>
  );
};
```

This uses reacts `setState` method and throws the provided error inside its callback. This is not a officially supported feature, so use with caution.

---

I will have to do some research before considering this as a possible feature.

**Comment by fxb-creator** [comment]
Thanks for the feedback and explanation 👍
