### ISSUE TITLE
is this will work for only if props are undefined? 

### ISSUE THREAD

**Issue by sonusandeep** [JoschuaSchneider/use-error-boundary#6]
I am writing api requests using saga, whenever any error occurred it will get it from the catch,

lets suppose if there is any error,  i am able to get the error details in the saga but when i use this npm package in my containers , in that case, it was not showing the error boundary component. 
Please clarifiy

**Comment by JoschuaSchneider** [comment]
Could you provide some example of how you intend to use the ErrorBoundary?

The core concept of this is that you get the error and errorInfo from the error boundary as state within your functional component.

You can either control what gets rendered when an error occurs yourself, or pass two render functions as props to the error boundary component.

**Comment by JoschuaSchneider** [comment]
By default, if you dont pass the `render` or `renderError` props, the boundary will render nothing.

This is because I want this component to be unopinionated about how you display the errors.

So you can render your error information using those props, or using the state you get from the hook.

**Comment by sonusandeep** [comment]
Hi @JoschuaSchneider ,
Thanks for your reply, yeah i am passing render and renderError, my screen has a table that has a data that will be called from API inside the each there will be another nester row that some text area and update functionality, these both have different APIs.

I have created an error component, in my container, I am wrapper the table with error boundary, in the render, i am passing the table and render error I am passing my error component to display when in error scenarios.

the code will belike

`export function abc(props){


const expand ={

logic to display the nested row 

}

const columns ={

}

 const {
    ErrorBoundary, // class - The react component to wrap your children in. This WILL NOT CHANGE 
    didCatch, // boolean - Whether the ErrorBoundary catched something
    error, // null or the error
    errorInfo // null or the error info as described in the react docs
  } = useErrorBoundary()


return(

 <ErrorBoundary
       render={() => <Tablenext 
     data={props.notes.info}
    columns={columns}
    expandRow={expand }
 />}
    renderError={({ error }) => <MyErrorComponent error={props.error} />}
  />
)

`

I am writing saga for data fetching from API, if any error happens i am able to get the details inside the catch block at saga, same wise if the  table data api has issue, in that case my props.notes.info will be undefined and i am able to see the renderError component and props.error will give the error info from catch block.

But in the nested row, if there is any  error occurred I am not able to get the render error display.

Any thing i am missing or do we have any limitation to this package like it will be displayed in one instance?

Thank you

**Comment by JoschuaSchneider** [comment]
@sonusandeep I'm not sure what you mean exactly.

The ErrorBoundary component is just a normal React class component utilizing the error boundary api, so the same limitations apply.

It seems that you are using it the right way in your example. And the error boundary should catch any error that happens in any of the child components.

You should also note that error boundaries only catch synchronous errors and can't catch errors from callbacks or async code ([Error Boundaries Docs](https://reactjs.org/docs/error-boundaries.html))

Are you nesting multiple ErrorBoundaries or are you just using that top-level one? And are you trying to catch errors from your asynchronous requests?

**Comment by sonusandeep** [comment]
Hi @JoschuaSchneider 
Yes i am using the error boundary's to catch the errors from the asynchronous request (saga calls) and I am nesting the error boundary for only one time as per the above example.

Soi am using it in a  functional component, i have imported the package and declared the 
```
const {
    ErrorBoundary, // class - The react component to wrap your children in. This WILL NOT CHANGE 
    didCatch, // boolean - Whether the ErrorBoundary catched something
    error, // null or the error
    errorInfo // null or the error info as described in the react docs
  } = useErrorBoundary()
```

then i wrapped my components with two functions render () and renderError()

It was working for the first time, like example when the table data is 404 or anything then i am able to see the component that i am rendering from the renderError().

But for the same case, if the update or any other request has been failed, i am not able to see this is
going to renderError() again. Example as my above code

`<ErrorBoundary
render={() => <Tablenext
data={props.notes.info}
columns={columns}
expandRow={expand }
/>}
renderError={({ error }) => }
/>`

if the data api from the table has an issue, i am getting an error from saga catch block and able to display the renderError().
 
The same case above if you see we have expandRow that has expand, which is a logic written to display another sub row upon clicking each row. This has a different API call, lets suppose if this has been failed then, the error will be caught at saga, and props defined inside expand row becomes undefined. This i am unable to get the error boundary displayed for render error().

Thank you for your continuous support

**Comment by JoschuaSchneider** [comment]
@sonusandeep it sounds like you are trying to catch errors that occur after the components render, if your API requests fail those errors can't be catched by React error boundaries (or this package).

They are designed to catch errors at render time, so any callbacks or async requests can't be handled.

```js
function MyComponent() {
   someRequest(() => {
      throw new Error() // This can't be catched by Error Boundaries
   })

   return (
      <div>
         {throw new Error()} // This will be catched by Error Boundaries
      </div>
   )
}
```

If you are using your requests as hooks you could build a custom hook that uses context to inform your wrapper component about nested errors.

There would be many solutions to this.

I hope I understood what your problem is.

**Comment by JoschuaSchneider** [comment]
Closing, problem does not seem to be related to the library, rather to ErrorBoundaries in general.
