### ISSUE TITLE
Example errors after didCatch

### ISSUE THREAD

**Issue by apekearo** [JoschuaSchneider/use-error-boundary#7]
Hello,  I'm looking forward to implementing your tool into my app, it looks like it will be exactlly what I need, thank you.  I'm contacting you because your example code creates an error at didCatch  in both the npm 'run kit' and in my VScode. I wanted to ask if there is some issue going on that could be causing this error?  The curly brackets can be removed after the return statement begins to get it to run without error, but it seems like those are important.  I'm really looking forward to using your package.  Thanks again.
![use-error-boundary](https://user-images.githubusercontent.com/15948415/82580825-52afcd80-9b55-11ea-91f4-915b771de0d7.png)
![errorboundaryVScode](https://user-images.githubusercontent.com/15948415/82580830-55aabe00-9b55-11ea-906f-64cc81cd64e3.png)

**Comment by apekearo** [comment]
I'm being told I need to build one from scratch, : (  I was liking how convenient your was.  Thanks again.

**Comment by JoschuaSchneider** [comment]
Hey, sorry for reopening this!

This is an **error with the syntax in my example**, I will fix that asap.

You would just have to remove one set of the curly-braces on line 17 and 24 to fix that on your side, or wrap another element around them.
